<MainPage>
	BoxLayout:
		#Orientation uses vertical or horizontal to determine the direction of the layout
		orientation: "vertical"
		size: root.width, root.height
		#padding adds a buffer from the edge of the layout,
		#spacing adds a buffer between the widgets in the layout
		padding: 50
		spacing: 20



		Button:
			text: "Hello World!"
			pos_hint: {"center_x": 0.5, "center_y": 0.5}
			size_hint:(None, None)
			width: 100
			height: 50
		Button:
			text: "Goodbye cruel world!"
			pos_hint: {"center_x": 0.5, "center_y": 0.5}
			size_hint:(None, None)
			width: 100
			height: 50