#:kivy 1.0.9

<MainPage>:
	canvas:
		Rectangle:
			pos: self.center_x + 200, 600
			size: 10, 110
		Rectangle:
			pos: self.center_x - 200, 600
			size: 10, 100
		Rectangle:
			pos: self.center_x - 200, 600
			size: 400, 10
		Rectangle:
			pos: self.center_x - 200, 700
			size: 400, 10
		Rectangle:
			pos: 0, 0
			size: 100, 100
			
	Label:
        font_size: 40  
        center_x: root.width / 2
        top: root.top - 50
        text: "[BuddyUp]"